# Generated by Django 4.2.7 on 2023-11-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_no', models.CharField(max_length=10, unique=True)),
                ('marks_hindi', models.IntegerField()),
                ('marks_english', models.IntegerField()),
                ('marks_math', models.IntegerField()),
                ('marks_science', models.IntegerField()),
                ('marks_grography', models.IntegerField()),
                ('photo', models.ImageField(upload_to='student_photos/')),
                ('class_level', models.IntegerField()),
            ],
        ),
    ]
